---
general:
  buildTool: "mta"
  verbose: true

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "jlabscforg"
    cfSpace: "devII"
    cfAppName: "cap-sflight"
    cfCredentialsId: "deploy-to-cf-sflight"
    uiVeri5ExecuteTests: false

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "jlabscforg"
    cfSpace: "devII"
    cfAppName: "cap-sflight"
    cfCredentialsId: "deploy-to-cf-sflight"
    tmsUpload: false
    verbose: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"

  npmExecuteLint:
    failOnError: true

  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"

  # tmsUpload:
  #   nodeName: "qa"
  #   credentialsId: "jlabsalertkey-sfligh"


